apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    day: day3
    sample: sample2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: kutti-delete