apiVersion: v1
kind: Secret
metadata:
  name: sec1
  labels:
    day: day3
    sample: secrets
stringData:
  dbpassword: somethingelse
  anotherpassword: whatever
  secretdata.txt: |
    This is a multiline string.
    This is the second line.
    This is the third line.
  onemorepassword: anything
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep4
  labels:
     day: day3
     sample: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      day: day3
      sample: secrets
      layer: dep4
  template:
    metadata:
      labels:
        day: day3
        sample: secrets
        layer: dep4
    spec:
      volumes:
        - name: secvol
          secret:
            secretName: sec1
      containers:
        - name: c1
          image: nginx:alpine
          volumeMounts:
            - name: secvol
              mountPath: /very/secret
          env:
            - name: VAR1
              valueFrom:
                secretKeyRef:
                  name: sec1
                  key: anotherpassword
