apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep2
  labels:
    day: day2
    sample: sample1
spec:
  selector:
    matchLabels:
      day: day2
      sample: sample1
      layer: dep2      
  template:
    metadata:
      labels:
        day: day2
        sample: sample1
        layer: dep2      
    spec:
      containers:
        - name: c1
          image: httpd:alpine
