apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
    day: day2
    sample: sample1
spec:
  type: ClusterIP
  selector:
    day: day2
    sample: sample1
    layer: dep1
  ports:
    - name: nginx
      port: 80
    - name: ics
      port: 81
      targetPort: 8080
