apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbapps.k8s.rajware.net
  labels:
    day: day5
    sample: crd
spec:
  group: k8s.rajware.net
  names:
    kind: DbApp
    listKind: DbAppList
    plural: dbapps
    singular: dbapp
    shortNames:
      - dba
    categories:
      - all
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              title: DbAppSpec
              description: |
                Specification of the desired state of the DBApp instance.
              properties:
                service:
                  type: object
                  description: Properties to configure the Service that exposes the Adminer front-end.
                  properties:
                    "type":
                      type: string
                      description: |
                        The type of Service that exposes the Adminer front-end. Can be 'NodePort' or 'LoadBalacer'. Default is 'NodePort.'
                      enum: 
                        - NodePort
                        - LoadBalancer
                      default: NodePort
                    nodePort:
                      type: integer
                      description: |
                        The node port of the Service that exposes the Adminer front-end. The range of values is 30000 to 32767. Omit to have a random port allocated. 
                      minimum: 30000
                      maximum: 32767
                      nullable: true
                db:
                  type: object
                  description: Properties to configure the Service that exposes the MySQL front-end.
                  properties:
                    storageCapacity:
                      type: string
                      description: The minimum required capacity of the PVC where the database data will be stored. Default value is 1Gi.
                      pattern: '^([0-9]+)([KMGT]i?)$'
                      default: 1Gi
                    storageClassName:
                      type: string
                      description: The storage class name assigned to the PVC. Omit to use the default storage class.
                      nullable: true
                    password:
                      type: string
                      description: The password for the root user
                    secretKey:
                      type: string
                      description: The key in a Secret object where the password will be stored. Omit to not create a Secret object.
                      nullable: true
                    secretName:
                      type: string
                      description: The name of the Secret object where the password will be stored. Ignored if the secretKey field is not set. Omit to auto-generate a name for the Secret object.
                      nullable: true
                  required:
                    - storageCapacity
                    - password
              required:
                - service
                - db
      additionalPrinterColumns:
        - name: ServiceType
          description: The type of Service that exposes the Adminer front-end
          type: string
          priority: 0
          jsonPath: .spec.service.type
        - name: DBCapacity
          description: The storage capacity of the MySQL back-end
          type: string 
          priority: 0
          jsonPath: .spec.db.storageCapacity
        - name: ServiceNodePort
          description: The node port of the service
          type: integer
          format: int32
          priority: 1
          jsonPath: .spec.service.nodePort
        - name: DBPassword
          description: The MySQL database password
          type: string
          format: password
          priority: 1
          jsonPath: .spec.db.password
      selectableFields:
        - jsonPath: .spec.service.type
        - jsonPath: .spec.service.nodePort